
APPID = 123456
SRVID = 777
AUTH_KEY = "aaaaaaaaaaaaaaa"
ROUND_TIME = 5
ROUND_COUNT = 5
A2B_ROUND_INTERVAL = 5
POLL_TIME = 10
TOTAL_ROUND_TIME = ROUND_TIME * ROUND_COUNT * 2 + A2B_ROUND_INTERVAL
BINGO_SCORE = 10
BC_SCORE_INTERVAL = 3
BC_POLLS_INTERVAL = 2
BC_VIP_INTERVAL = 5
STOP_REASON = {[1]="主播变化"}
